### ISSUE TITLE
Invalid ESM format for version 2.1.4

### ISSUE THREAD

**Issue by adrian-branescu** [planttheidea/fast-copy#71] opened 2022-09-23 10:23 UTC
When I import `fast-copy@2.1.4` as an ES module in Node.js I get the following error:
```javascript
(node:6782) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

/<my>/<absolute>/<path>/node_modules/fast-copy/dist/fast-copy.esm.js:346
export { copy as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
```

This is due to the fact that you added conditional `exports` key in `package.json`:
```javascript
"exports": {
    ".": {
        "require": "./dist/fast-copy.cjs.js",
        "import": "./dist/fast-copy.esm.js",
        "default": "./dist/fast-copy.js"
    }
},
```
but you didn't add `"type": "module"`, which is mandatory in order for the Node.js ESM Loader to correctly interpret your conditional exports. Because `"type": "module"` is missing, the following default policy is applied:
> Within a package, the [package.json](https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions) ["type"](https://nodejs.org/api/packages.html#type) field defines how Node.js should interpret .js files. If a package.json file does not have a "type" field, .js files are treated as [CommonJS](https://nodejs.org/api/modules.html).

as stated here https://nodejs.org/api/packages.html#packagejson-and-file-extensions

**Comment by planttheidea** [comment] 2022-09-23 10:46
Sorry about this! I have added the `"type": "module"` field as required in version `2.1.5`, which has just been published. Let me know if there are any more issues!

**Comment by adrian-branescu** [comment] 2022-09-23 12:04
> Sorry about this! I have added the `"type": "module"` field as required in version `2.1.5`, which has just been published. Let me know if there are any more issues!

Now there are two problems:
1. version `2.1.5` is not advertised as `latest` by `npmjs`, which might be a publish issue:
```bash
npm view fast-copy dist-tags.latest
```
outputs
```bash
2.1.4
```

2. the CommonJS is broken after adding `"type": "module"` because
> A package.json "type" value of "module" tells Node.js to interpret .js files within that package as using [ES module](https://nodejs.org/api/esm.html) syntax.

So the solution for this problem is to change:
> "require": "./dist/fast-copy.cjs.js",

to:

> "require": "./dist/fast-copy.cjs",

as stated in the [docs](https://nodejs.org/api/packages.html#packagejson-and-file-extensions):

> Within a "type": "module" package, Node.js can be instructed to interpret a particular file as [CommonJS](https://nodejs.org/api/modules.html) by naming it with a .cjs extension (since both .js and .mjs files are treated as ES modules within a "module" package).

**Comment by planttheidea** [comment] 2022-09-23 12:17
The former may be a caching issue. I used the same release process I use for all versions, so for it to suddenly fail would be surprising.

In terms of the latter, I read the same thing but separated "can" from "must". The documentation is ambiguous in the requirement to have that extension, and I explicitly avoided it to prevent a breaking change. Unfortunately, this seems to be necessary.

The two things I'll do:

1. Back out the changes in both `2.1.4` and `2.1.5` and publish a new version of what is essentially `2.1.3` as `2.1.6`. This will let caret consumers get the last good version of V2.
2. Apply all of these changes, including file renames, as v3. If I create a beta, would you be willing to validate? If like to avoid this kind of iteration on future "stable" versions if possible.

**Comment by Coniface** [comment] 2022-09-23 12:28
Thanks for raising/fixing the issue so fast!

My CI is currently broken because pino-pretty depends on the (currently) broken version of fast-copy.

**Comment by revolunet** [comment] 2022-09-23 12:35
same here with node 18 : 

```
const fastCopy = require('fast-copy')
                 ^
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/julienb/projects/mas/testfast/node_modules/fast-copy/dist/fast-copy.cjs.js from /Users/julienb/projects/mas/testfast/node_modules/pino-pretty/lib/utils.js not supported.
fast-copy.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename fast-copy.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/julienb/projects/mas/testfast/node_modules/fast-copy/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

```

**Comment by planttheidea** [comment] 2022-09-23 13:09
Alright, `2.1.7` has been published with revert of the changes. `2.1.6` was a bad publish (release process failed but still published ... need to look into that), but `2.1.7` was successful. Nothing seems to be going right this morning!

@adrian-branescu @Coniface @revolunet if you can confirm that the latest version resolves your issues, I'd appreciate it. In the meantime, I'll start work on v3 to reintroduce the intended changes from #69 .

**Comment by revolunet** [comment] 2022-09-23 13:14
Fixed here, thanks for the fast fix !

**Comment by Coniface** [comment] 2022-09-23 13:24
Many thanks @planttheidea I can confirm the fix!

You can enrich the README now _"A blazing fast deep object copier maintained by a blazing fast developer"_ :ok_hand:

**Comment by planttheidea** [comment] 2022-09-23 15:42
Thanks all! I'll close this issue, then.

@adrian-branescu @Coniface @revolunet @ilteoood - If you are willing, I've just published `3.0.0-beta.0` of `fast-copy`. This provides the `exports` addition in what should be a better format, and also hopefully better typing. Note: I took the opportunity to make a long-standing change of removing default export in favor of named exports (`import { copy }` instead of `import copy`. If any of you are willing, though, to test out that version ... I would be most appreciative! The changes from #69 are positive, so I'd like to include them as soon as I can.

**Closed by planttheidea** 2022-09-23 15:42 UTC

**Comment by ilteoood** [comment] 2022-09-23 16:40
I don't understand this sentence
 
> The documentation is ambiguous in the requirement to have that extension, and I explicitly avoided it to prevent a breaking change. Unfortunately, this seems to be necessary.

If you leave the type module and also change `main` field to remove the `js` extension, node or the bundler should do the rest of the work, without any kind of breaking change.
What am I missing?

**Comment by planttheidea** [comment] 2022-09-23 16:57
@ilteoood by changing one of the distributable files, I am indeed considering it a breaking change. For those that deep-link to the module or have set up aliases in their build configuration, this would cause failures. I realize it was recommended above as the solution, but I could not in good conscience call it a patch when it could knowingly break automated build systems.

I am actively working to incorporate your change on version 3, as you have already noted.
